// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/index.tsx";
import * as $1 from "./routes/walking.tsx";
import * as $2 from "./routes/walking/202303.tsx";
import * as $3 from "./routes/walking/202307.tsx";
import * as $4 from "./routes/walking/202308.tsx";
import * as $5 from "./routes/walking/202310.tsx";
import * as $6 from "./routes/walking/202311.tsx";
import * as $7 from "./routes/walking/france.tsx";
import * as $8 from "./routes/walking/germany.tsx";
import * as $9 from "./routes/walking/ireland.tsx";
import * as $10 from "./routes/walking/japan.tsx";
import * as $11 from "./routes/walking/netherlands.tsx";
import * as $12 from "./routes/walking/scotland.tsx";
import * as $13 from "./routes/walking/uk.tsx";

const manifest = {
  routes: {
    "./routes/index.tsx": $0,
    "./routes/walking.tsx": $1,
    "./routes/walking/202303.tsx": $2,
    "./routes/walking/202307.tsx": $3,
    "./routes/walking/202308.tsx": $4,
    "./routes/walking/202310.tsx": $5,
    "./routes/walking/202311.tsx": $6,
    "./routes/walking/france.tsx": $7,
    "./routes/walking/germany.tsx": $8,
    "./routes/walking/ireland.tsx": $9,
    "./routes/walking/japan.tsx": $10,
    "./routes/walking/netherlands.tsx": $11,
    "./routes/walking/scotland.tsx": $12,
    "./routes/walking/uk.tsx": $13,
  },
  islands: {},
  baseUrl: import.meta.url,
  config,
};

export default manifest;
